---
# Global Ansible behavior
ansible_user: ansible
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_become: true
ansible_become_method: sudo

# Timezone consistency (important for logs & certs)
timezone: America/Chicago

# RKE2 version pinning (VERY important)
rke2_version: v1.29.3+rke2r1

# Cluster Token
rke2_token: "{{ lookup('ansible.builtin.env', 'RKE2_TOKEN') | quote }}"

# Networking
rke2_cni: canal          # simple + stable to start
disable_kube_proxy: false

# Ingress
rke2_ingress_controller: traefik

# Set my server and agent ansbile group names
rke2_servers_group_name: rke2_servers
rke2_agents_group_name: rke2_agents
rke2_cluster_group_name: rke2_cluster

# vars required by the lablabs.rke2 role
rke2_node_name: "{{ inventory_hostname }}"
rke2_snapshotter: overlayfs

rke2_cluster_cidr:
  - 10.42.0.0/16
rke2_service_cidr:
  - 10.43.0.0/16

rke2_additional_sans: []
k8s_node_label: []
